import { ArrowUpRight, CircleAlert, Plus, TrendingUp } from "lucide-react";
import Link from "next/link";
import { money } from "@/lib/accounting";
import { getDashboardSnapshot } from "@/lib/dashboard";

const cardLabels = [
  ["Facturado", "billed"], ["Rentabilidad", "profitability"], ["Pago a choferes", "driverPayments"], ["Gastos SRI", "taxExpenses"],
] as const;

export default async function DashboardPage() {
  const data = await getDashboardSnapshot();
  const max = Math.max(...data.monthly.map((row) => row.billed), 1);
  return <div className="mx-auto max-w-7xl px-5 py-8 sm:px-8">
    <header className="mb-8 flex flex-wrap items-end justify-between gap-4"><div><p className="mb-1 text-sm font-medium text-[var(--accent)]">Enero — Diciembre 2026</p><h1 className="text-3xl font-semibold tracking-tight">Resumen financiero</h1><p className="mt-2 text-sm text-[var(--muted)]">Ingresos, rentabilidad y obligaciones en un solo lugar.</p></div><Link href="/guias/nueva" className="inline-flex items-center gap-2 rounded-lg bg-[var(--accent)] px-4 py-2.5 text-sm font-medium text-white"><Plus size={17} />Registrar guía</Link></header>
    {data.isDemo && <div className="mb-6 flex items-center gap-2 rounded-xl border border-[#d7e7dc] bg-[var(--accent-soft)] px-4 py-3 text-sm text-[#23563e]"><CircleAlert size={17} />Vista de referencia basada en el libro actual. Conecte Supabase e importe el archivo para operar con datos reales.</div>}
    <section className="grid gap-4 sm:grid-cols-2 xl:grid-cols-4">{cardLabels.map(([label, key]) => <article key={key} className="rounded-xl border border-[var(--line)] bg-[var(--card)] p-5"><p className="text-sm text-[var(--muted)]">{label}</p><p className="mt-3 text-2xl font-semibold tracking-tight">{money.format(data.totals[key])}</p><span className="mt-3 inline-flex items-center gap-1 text-xs font-medium text-[var(--accent)]"><TrendingUp size={14} />Acumulado del período</span></article>)}</section>
    <section className="mt-6 grid gap-6 xl:grid-cols-[1.4fr_1fr]"><article className="rounded-xl border border-[var(--line)] bg-white p-5"><div className="mb-6 flex items-center justify-between"><div><h2 className="font-semibold">Facturación mensual</h2><p className="text-sm text-[var(--muted)]">Costo original de guías registradas</p></div><span className="text-xs text-[var(--muted)]">USD</span></div><div className="flex h-52 items-end gap-3">{data.monthly.map((row) => <div className="flex h-full flex-1 flex-col justify-end" key={row.month}><div className="group relative rounded-t-md bg-[var(--accent)]/90 transition hover:bg-[var(--accent)]" style={{ height: `${Math.max((row.billed / max) * 100, 4)}%` }} title={`${row.month}: ${money.format(row.billed)}`} /><span className="mt-2 text-center text-xs text-[var(--muted)]">{row.month}</span></div>)}</div></article>
      <article className="rounded-xl border border-[var(--line)] bg-white p-5"><h2 className="font-semibold">Reglas automatizadas</h2><p className="mt-1 text-sm text-[var(--muted)]">Se calculan al guardar cada guía.</p><dl className="mt-5 space-y-4 text-sm"><div className="flex justify-between border-b border-[var(--line)] pb-3"><dt>Rentabilidad</dt><dd className="font-mono text-xs">costo × porcentaje</dd></div><div className="flex justify-between border-b border-[var(--line)] pb-3"><dt>Pago al chofer</dt><dd className="font-mono text-xs">costo − rentabilidad − abono</dd></div><div className="flex justify-between"><dt>Transferencia</dt><dd className="font-mono text-xs">pago − comisión</dd></div></dl></article></section>
    <section className="mt-6 rounded-xl border border-[var(--line)] bg-white"><div className="flex items-center justify-between p-5"><div><h2 className="font-semibold">Últimas guías</h2><p className="text-sm text-[var(--muted)]">Movimientos operativos recientes</p></div><Link href="/guias" className="inline-flex items-center gap-1 text-sm font-medium text-[var(--accent)]">Ver todas <ArrowUpRight size={16} /></Link></div><div className="overflow-x-auto"><table className="w-full min-w-[720px] text-left text-sm"><thead className="border-y border-[var(--line)] bg-[#fafbfa] text-xs uppercase tracking-wide text-[var(--muted)]"><tr><th className="px-5 py-3 font-medium">Fecha</th><th className="px-5 py-3 font-medium">Chofer</th><th className="px-5 py-3 font-medium">Factura</th><th className="px-5 py-3 font-medium">Costo</th><th className="px-5 py-3 font-medium">Rentabilidad</th><th className="px-5 py-3 font-medium">Estado</th></tr></thead><tbody>{data.guides.map((guide) => <tr key={guide.id} className="border-b border-[var(--line)] last:border-0"><td className="px-5 py-4 text-[var(--muted)]">{guide.date}</td><td className="px-5 py-4"><strong className="font-medium">{guide.driver}</strong><span className="ml-2 text-xs text-[var(--muted)]">{guide.vehicle}</span></td><td className="px-5 py-4">{guide.invoice}</td><td className="px-5 py-4 font-mono text-xs">{money.format(guide.originalCost)}</td><td className="px-5 py-4 font-mono text-xs text-[var(--accent)]">{money.format(guide.profitability)}</td><td className="px-5 py-4"><span className="rounded-full bg-[#edf4ef] px-2.5 py-1 text-xs font-medium text-[#356247]">{guide.status}</span></td></tr>)}</tbody></table></div></section>
  </div>;
}
