"use client";

import Link from "next/link";
import { useActionState, useState } from "react";
import { createBalanceEntry, type BalanceActionState } from "@/app/actions/balances";

const initialState: BalanceActionState = {};

export function NewBalanceEntryForm() {
  const [state, formAction, isPending] = useActionState(createBalanceEntry, initialState);
  const [entryType, setEntryType] = useState("opening_balance");
  return <form action={formAction} className="mt-7 grid gap-6 xl:grid-cols-[1fr_300px]"><section className="rounded-xl border border-[var(--line)] bg-white p-6"><div className="grid gap-5 sm:grid-cols-2"><label className="text-sm font-medium">Socio<select required name="shareholder" defaultValue="" className="mt-1.5 w-full rounded-lg border border-[var(--line)] bg-white px-3 py-2.5 text-sm"><option value="" disabled>Seleccione un socio</option><option>Daniel</option><option>Jorge</option><option>Favio</option></select></label><label className="text-sm font-medium">Fecha<input required name="movement_date" type="date" className="mt-1.5 w-full rounded-lg border border-[var(--line)] px-3 py-2.5 text-sm outline-none focus:border-[var(--accent)]" /></label><label className="text-sm font-medium">Tipo de movimiento<select name="entry_type" value={entryType} onChange={(event) => setEntryType(event.target.value)} className="mt-1.5 w-full rounded-lg border border-[var(--line)] bg-white px-3 py-2.5 text-sm"><option value="opening_balance">Saldo inicial / aporte</option><option value="adjustment_credit">Ajuste a favor</option><option value="adjustment_debit">Ajuste en contra</option><option value="withdrawal">Retiro de dinero</option></select></label><label className="text-sm font-medium">Valor (USD)<input required name="amount" type="number" min="0.01" step="0.01" placeholder="0.00" className="mt-1.5 w-full rounded-lg border border-[var(--line)] px-3 py-2.5 text-sm outline-none focus:border-[var(--accent)]" /></label></div><label className="mt-5 block text-sm font-medium">Motivo / descripción {entryType === "withdrawal" && <span className="text-[#a85625]">(obligatorio para retiros)</span>}<textarea required={entryType === "withdrawal"} name="description" rows={3} placeholder={entryType === "withdrawal" ? "Ej. Retiro por gastos personales" : "Detalle opcional del movimiento"} className="mt-1.5 w-full resize-none rounded-lg border border-[var(--line)] px-3 py-2.5 text-sm outline-none focus:border-[var(--accent)]" /></label>{state.error && <p role="alert" className="mt-5 rounded-lg bg-[#fdefec] px-4 py-3 text-sm text-[#963f32]">{state.error}</p>}<div className="mt-7 flex justify-end gap-3"><Link href="/saldos" className="rounded-lg px-4 py-2.5 text-sm font-medium">Cancelar</Link><button disabled={isPending} className="rounded-lg bg-[var(--accent)] px-4 py-2.5 text-sm font-medium text-white disabled:opacity-60">{isPending ? "Guardando…" : "Guardar movimiento"}</button></div></section><aside className="h-fit rounded-xl bg-[#173e30] p-5 text-white"><p className="text-sm font-medium text-[#b8dac8]">Cómo afecta el saldo</p><h2 className="mt-1 text-lg font-semibold">Libro mayor automático</h2><p className="mt-5 text-sm leading-6 text-[#d5e8dd]">Los saldos iniciales y ajustes a favor suman disponibilidad. Los retiros y pagos de guías pagadas descuentan automáticamente el saldo del socio.</p></aside></form>;
}
