"use client";

import Link from "next/link";
import { useActionState, useState } from "react";
import { createCompanyExpense, type ExpenseActionState } from "@/app/actions/expenses";

const initialState: ExpenseActionState = {};

export function NewCompanyExpenseForm() {
  const [state, formAction, isPending] = useActionState(createCompanyExpense, initialState);
  const [movementType, setMovementType] = useState("expense");
  return <form action={formAction} className="mt-7 grid gap-6 xl:grid-cols-[1fr_280px]"><section className="rounded-xl border border-[var(--line)] bg-white p-6"><div className="grid gap-5 sm:grid-cols-2"><label className="text-sm font-medium">Fecha<input required name="date" type="date" className="mt-1.5 w-full rounded-lg border border-[var(--line)] px-3 py-2.5 text-sm outline-none focus:border-[var(--accent)]" /></label><label className="text-sm font-medium">Movimiento<select name="movement_type" value={movementType} onChange={(event) => setMovementType(event.target.value)} className="mt-1.5 w-full rounded-lg border border-[var(--line)] bg-white px-3 py-2.5 text-sm"><option value="expense">Egreso</option><option value="income">Ingreso</option></select></label><label className="text-sm font-medium sm:col-span-2">Concepto<input required name="concept" placeholder={movementType === "income" ? "Ej. Cobro de servicio" : "Ej. Compra de combustible"} className="mt-1.5 w-full rounded-lg border border-[var(--line)] px-3 py-2.5 text-sm outline-none focus:border-[var(--accent)]" /></label><label className="text-sm font-medium">Tipo / categoría<input name="type" placeholder="Ej. Operativo, administrativo" className="mt-1.5 w-full rounded-lg border border-[var(--line)] px-3 py-2.5 text-sm outline-none focus:border-[var(--accent)]" /></label><label className="text-sm font-medium">Beneficiario<input name="beneficiary" placeholder={movementType === "income" ? "Cliente o pagador" : "Proveedor o persona"} className="mt-1.5 w-full rounded-lg border border-[var(--line)] px-3 py-2.5 text-sm outline-none focus:border-[var(--accent)]" /></label><label className="text-sm font-medium">Valor (USD)<input required name="amount" type="number" min="0.01" step="0.01" placeholder="0.00" className="mt-1.5 w-full rounded-lg border border-[var(--line)] px-3 py-2.5 text-sm outline-none focus:border-[var(--accent)]" /></label></div>{state.error && <p role="alert" className="mt-5 rounded-lg bg-[#fdefec] px-4 py-3 text-sm text-[#963f32]">{state.error}</p>}<div className="mt-7 flex justify-end gap-3"><Link href="/gastos-empresa" className="rounded-lg px-4 py-2.5 text-sm font-medium">Cancelar</Link><button disabled={isPending} className="rounded-lg bg-[var(--accent)] px-4 py-2.5 text-sm font-medium text-white disabled:opacity-60">{isPending ? "Guardando…" : `Guardar ${movementType === "income" ? "ingreso" : "egreso"}`}</button></div></section><aside className="h-fit rounded-xl bg-[#173e30] p-5 text-white"><p className="text-sm font-medium text-[#b8dac8]">Libro de control</p><h2 className="mt-1 text-lg font-semibold">Saldo acumulado</h2><p className="mt-4 text-sm leading-6 text-[#d5e8dd]">Los ingresos suman y los egresos restan del saldo operativo. El orden se conserva por fecha, como en la hoja de Control de gastos 2026.</p></aside></form>;
}
