import { ArrowDownRight, ArrowUpRight, Plus } from "lucide-react";
import Link from "next/link";
import { money } from "@/lib/accounting";
import { getBalanceSnapshot } from "@/lib/balances";

export default async function BalancesPage() {
  const { balances, entries, isDemo } = await getBalanceSnapshot();
  return <div className="mx-auto max-w-6xl px-5 py-8 sm:px-8"><header className="flex flex-wrap items-end justify-between gap-4"><div><p className="mb-1 text-sm font-medium text-[var(--accent)]">Capital disponible</p><h1 className="text-3xl font-semibold tracking-tight">Saldos por socio</h1><p className="mt-2 text-sm text-[var(--muted)]">Cada pago de guía y retiro queda descontado con su motivo.</p></div><Link href="/saldos/nuevo" className="inline-flex items-center gap-2 rounded-lg bg-[var(--accent)] px-4 py-2.5 text-sm font-medium text-white"><Plus size={17}/>Registrar movimiento</Link></header>{isDemo && <p className="mt-6 rounded-lg bg-[#fff7df] px-4 py-3 text-sm text-[#765c1c]">Vista de ejemplo. Los saldos reales aparecerán al ejecutar la migración de libro mayor en Supabase.</p>}<section className="mt-6 grid gap-4 md:grid-cols-3">{balances.map((balance) => <article key={balance.shareholder} className="rounded-xl border border-[var(--line)] bg-white p-5"><p className="text-sm text-[var(--muted)]">Saldo disponible · {balance.shareholder}</p><strong className={`mt-3 block text-2xl ${balance.availableBalance < 0 ? "text-[#b04a39]" : "text-[var(--accent)]"}`}>{money.format(balance.availableBalance)}</strong><dl className="mt-5 space-y-2 border-t border-[var(--line)] pt-4 text-xs"><div className="flex justify-between"><dt className="text-[var(--muted)]">Guías pagadas</dt><dd>{money.format(balance.paidGuides)}</dd></div><div className="flex justify-between"><dt className="text-[var(--muted)]">Retiros</dt><dd>{money.format(balance.withdrawals)}</dd></div></dl></article>)}</section><section className="mt-6 overflow-hidden rounded-xl border border-[var(--line)] bg-white"><div className="border-b border-[var(--line)] px-5 py-4"><h2 className="font-semibold">Movimientos recientes</h2></div><div className="overflow-x-auto"><table className="w-full min-w-[720px] text-left text-sm"><thead className="bg-[#fafbfa] text-xs uppercase tracking-wide text-[var(--muted)]"><tr><th className="px-5 py-3">Fecha</th><th className="px-5 py-3">Socio</th><th className="px-5 py-3">Movimiento</th><th className="px-5 py-3">Motivo</th><th className="px-5 py-3">Valor</th></tr></thead><tbody>{entries.map((entry) => <tr key={entry.id} className="border-t border-[var(--line)]"><td className="px-5 py-4 text-[var(--muted)]">{entry.date}</td><td className="px-5 py-4 font-medium">{entry.shareholder}</td><td className="px-5 py-4">{entry.type}</td><td className="px-5 py-4 text-[var(--muted)]">{entry.description ?? "—"}</td><td className={`px-5 py-4 font-mono text-xs ${entry.direction === "credit" ? "text-[var(--accent)]" : "text-[#b04a39]"}`}><span className="mr-1 inline-block align-middle">{entry.direction === "credit" ? <ArrowUpRight size={14}/> : <ArrowDownRight size={14}/>}</span>{entry.direction === "credit" ? "+" : "−"}{money.format(entry.amount)}</td></tr>)}</tbody></table></div></section></div>;
}
