"use server";
import { revalidatePath } from "next/cache";
import { redirect } from "next/navigation";
import { getSupabaseServerClient } from "@/lib/supabase/server";
export type ExpenseActionState = { error?: string };

export async function createTaxExpense(_: ExpenseActionState, formData: FormData): Promise<ExpenseActionState> {
  try { const supabase = await getSupabaseServerClient(); if (!supabase) return { error: "Configure Supabase antes de registrar gastos." }; const { data: membership } = await supabase.from("organization_members").select("organization_id").limit(1).single(); if (!membership) return { error: "Sin organización asignada." }; const supplier = String(formData.get("supplier") ?? "").trim(); const date = String(formData.get("date") ?? ""); const subtotal = Number(formData.get("subtotal")); const vat = Number(formData.get("vat") || 0); if (!supplier || !date || !Number.isFinite(subtotal) || subtotal < 0 || !Number.isFinite(vat) || vat < 0) return { error: "Complete proveedor, fecha, subtotal e IVA." }; const { error } = await supabase.from("tax_expenses").insert({ organization_id: membership.organization_id, issue_date: date, authorization_date: String(formData.get("authorization_date") ?? "").trim() || null, supplier_ruc: String(formData.get("ruc") ?? "").trim() || null, supplier_name: supplier, receipt_type: String(formData.get("receipt_type") ?? "").trim() || "Factura", receipt_number: String(formData.get("receipt") ?? "").trim() || null, access_key: String(formData.get("access_key") ?? "").trim() || null, recipient_identification: String(formData.get("recipient") ?? "").trim() || null, subtotal, vat, total: subtotal + vat, assigned_to: String(formData.get("shareholder") ?? "").trim() || null }); if (error) return { error: error.message }; revalidatePath("/gastos"); revalidatePath("/"); } catch (error) { return { error: error instanceof Error ? error.message : "No se pudo guardar el gasto SRI." }; } redirect("/gastos");
}

export async function createCompanyExpense(_: ExpenseActionState, formData: FormData): Promise<ExpenseActionState> {
  try { const supabase = await getSupabaseServerClient(); if (!supabase) return { error: "Configure Supabase antes de registrar movimientos." }; const { data: membership } = await supabase.from("organization_members").select("organization_id").limit(1).single(); if (!membership) return { error: "Sin organización asignada." }; const concept = String(formData.get("concept") ?? "").trim(); const date = String(formData.get("date") ?? ""); const amount = Number(formData.get("amount")); const movementType = String(formData.get("movement_type") ?? "expense"); if (!concept || !date || !Number.isFinite(amount) || amount <= 0 || !["income", "expense"].includes(movementType)) return { error: "Complete fecha, concepto, tipo y valor." }; const { error } = await supabase.from("expenses").insert({ organization_id: membership.organization_id, expense_date: date, concept, expense_type: String(formData.get("type") ?? "").trim() || null, beneficiary: String(formData.get("beneficiary") ?? "").trim() || null, movement_type: movementType, amount }); if (error) return { error: error.message }; revalidatePath("/gastos-empresa"); revalidatePath("/"); } catch (error) { return { error: error instanceof Error ? error.message : "No se pudo guardar el movimiento." }; } redirect("/gastos-empresa");
}
