import { FileWarning, Plus } from "lucide-react";
import Link from "next/link";
import { money } from "@/lib/accounting";
import { InvoiceTable } from "@/components/invoice-table";
import { getInvoiceSnapshot } from "@/lib/invoices";

export default async function InvoicesPage({ searchParams }: { searchParams: Promise<{ filtro?: string }> }) {
  const params = await searchParams;
  const expiring = params.filtro === "caducar";
  const { invoices, isDemo } = await getInvoiceSnapshot();
  const totalAssigned = invoices.reduce((sum, invoice) => sum + invoice.totalAmount, 0);
  const profitByPartner = invoices.flatMap((invoice) => invoice.allocations).reduce<Record<string, number>>((totals, allocation) => ({ ...totals, [allocation.shareholder]: (totals[allocation.shareholder] ?? 0) + allocation.guideProfitability }), {});
  return <div className="mx-auto max-w-6xl px-5 py-8 sm:px-8"><header className="flex flex-wrap items-end justify-between gap-4"><div><p className="mb-1 text-sm font-medium text-[var(--accent)]">Facturación manual</p><h1 className="text-3xl font-semibold tracking-tight">{expiring ? "Facturas por caducar" : "Facturas y distribución"}</h1><p className="mt-2 text-sm text-[var(--muted)]">Registre valores por socio y consulte la ganancia generada por las guías vinculadas.</p></div><Link href="/facturas/nueva" className="inline-flex items-center gap-2 rounded-lg bg-[var(--accent)] px-4 py-2.5 text-sm font-medium text-white"><Plus size={17}/>Nueva factura</Link></header>{isDemo && <p className="mt-6 rounded-lg bg-[#fff7df] px-4 py-3 text-sm text-[#765c1c]">Ejemplo de distribución. Los valores reales aparecerán al conectar Supabase y registrar facturas.</p>}<section className="mt-6 grid gap-4 md:grid-cols-4"><article className="rounded-xl border border-[var(--line)] bg-white p-5 md:col-span-1"><p className="text-sm text-[var(--muted)]">Facturado distribuido</p><strong className="mt-3 block text-2xl">{money.format(totalAssigned)}</strong></article>{["Daniel", "Jorge", "Favio"].map((partner) => <article key={partner} className="rounded-xl border border-[var(--line)] bg-white p-5"><p className="text-sm text-[var(--muted)]">Ganancia · {partner}</p><strong className="mt-3 block text-2xl text-[var(--accent)]">{money.format(profitByPartner[partner] ?? 0)}</strong><span className="mt-2 block text-xs text-[var(--muted)]">De guías con factura vinculada</span></article>)}</section>{invoices.length ? <InvoiceTable invoices={invoices}/> : <section className="mt-7 rounded-xl border border-[var(--line)] bg-white p-8 text-center"><FileWarning className="mx-auto text-[var(--accent)]" size={28}/><h2 className="mt-4 font-semibold">Aún no hay facturas registradas</h2><p className="mx-auto mt-2 max-w-md text-sm text-[var(--muted)]">Registre la primera factura para distribuir el valor entre socios y llevar el cálculo de ganancia.</p></section>}</div>;
}
